const groceryDb = [
  {
    name: "Bread",
    quantity: "5",
    category: "Red",
    addedBy: "Nancy",
    addedOn: new Date(2020, 4, 8),
    isBought: false,
  },
  {
    name: "Water",
    quantity: "2L",
    category: "Blue",
    addedBy: "Fred",
    addedOn: new Date(2020, 3, 25),
    isBought: false,
  },
  {
    name: "Cheese",
    quantity: "50",
    category: null,
    addedBy: "Aya",
    addedOn: new Date(2020, 1, 30),
    isBought: true,
    boughtBy: "Fred",
    boughtOn: new Date(2020, 2, 1),
    price: 50,
  },
  {
    name: "Wine",
    quantity: "3L",
    category: null,
    addedBy: "Marcel",
    addedOn: new Date(2020, 2, 2),
    isBought: true,
    boughtBy: "Charles",
    boughtOn: new Date(2020, 2, 10),
    price: 15,
  },
  {
    name: "Beer",
    quantity: "5L",
    category: null,
    addedBy: "Marcel",
    addedOn: new Date(2020, 2, 2),
    isBought: true,
    boughtBy: "Julia",
    boughtOn: new Date(2020, 2, 10),
    price: 20,
  },
  {
    name: "M&M's",
    quantity: "5kg",
    category: null,
    addedBy: "Didier",
    addedOn: new Date(2020, 1, 4),
    isBought: true,
    boughtBy: "Charles",
    boughtOn: new Date(2020, 3, 5),
    price: 20,
  },

];

export default groceryDb;
